version: "3.9"

services:
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-c*poozxl7cl)uwd79$o&c5!$mo*0(=nmsoux4qkb5a!g+^26dw"
      - "DJANGO_DEBUG=True"
#        Google OAuth2 configuration
      - "GOOGLE_CLIENT_ID=YOUR_CLIENT_ID"
      - "GOOGLE_SECRET=YOUR_SECRET_KEY"
#        SMTP configuration
      - "DJANGO_EMAIL_HOST=YOUR_HOST"
      - "DJANGO_HOST_USER=YOUR_HOST_USER"
      - "DJANGO_HOST_PASSWORD=YOUR_HOST_PASSWORD"
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:


